</$objtype/mkfile

LIB=libfreetype.a$O
OFILES=\
	src/base/ftbase.$O \
		ftsystem.$O \
		ftinit.$O \
		ftdebug.$O \
		ftbitmap.$O \
		ftglyph.$O \
		ftmm.$O \
	src/autofit/autofit.$O \
	src/bdf/bdf.$O \
	src/cache/ftcache.$O \
	src/cff/cff.$O \
	src/cid/type1cid.$O \
	src/pcf/pcf.$O \
	src/pfr/pfr.$O \
	src/psaux/psaux.$O \
	src/pshinter/pshinter.$O \
	src/psnames/psnames.$O \
	src/raster/raster.$O \
	src/sdf/sdf.$O \
	src/sfnt/sfnt.$O \
	src/smooth/smooth.$O \
	src/svg/svg.$O \
	src/truetype/truetype.$O \
	src/type1/type1.$O \
	src/type42/type42.$O \
	src/winfonts/winfnt.$O \

HFILES=\
	builds/plan9/ft2build.h \
	builds/plan9/p9ftoptions.h \

CFLAGS=-p -I./builds/plan9 -I./include -DFT2_BUILD_LIBRARY

</sys/src/cmd/mklib

%.$O: %.c
	$CC $CFLAGS -o $stem.$O $stem.c
%.$O:	src/base/%.c
	$CC $CFLAGS src/base/$stem.c

clean:V:
	rm -f *.[$OS] src/*/*.[$OS] $CLEANFILES

nuke:V:
	rm -f *.[$OS] src/*/*.[$OS] $CLEANFILES
	rm -f libfreetype.a[$OS]
